[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dlib>=19.24.8",
    "face-recognition>=1.3.0",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.45.0",
]
